site_name: Satc - Eng de Dados Apache Spark
nav:
  - Início: index.md
  - Delta Lake: delta-lake.md
  - Iceberg: iceberg.md
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
